### PR TITLE
feat: add test result id into env var

### PR DESCRIPTION
**Pull request by xiukei**
### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by xiukei** [comment]
#54

**Comment by ZhouYixun** [comment]
作用是给下文传参？

**Comment by ZhouYixun** [comment]
https://github.com/jenkinsci/sonic-ci-helper-plugin/issues/53

**Review by yaming116 — APPROVED** [review]

**Comment by ZhouYixun** [comment]
I will release later

**Comment by ZhouYixun** [comment]
https://github.com/jenkinsci/sonic-ci-helper-plugin/releases/tag/sonic-ci-helper-1.0.5

**Pull request merged**
